"""
memory_bridge.py — SentientOS + NAS + WorkBuddy 记忆桥接模块

功能：
1. 读取 NAS 上 SentientOS 产出的每日摘要
2. 将知识注入 WorkBuddy 的记忆上下文
3. 双向同步：WorkBuddy 工作日志 → NAS / SentientOS 可读格式
"""

import os
import json
import shutil
from pathlib import Path
from datetime import datetime, timedelta
from typing import Optional

# 路径常量
NAS_KB_PATH = Path("/Volumes/NAS/sentient-nas-bridge/knowledge")
SENTIENT_DATA = NAS_KB_PATH / "sentient_data"
WBMEMORY = Path.home() / "WorkBuddy/Claw/.workbuddy/memory"
WBMEMORY_FILE = WBMEMORY / "MEMORY.md"
CONTEXT_FILE = WBMEMORY / "sentient_context.md"


class MemoryBridge:
    """SentientOS ↔ NAS ↔ WorkBuddy 记忆桥接"""

    def __init__(self, nas_path: Path = NAS_KB_PATH):
        self.nas_path = nas_path
        self.wb_memory = WBMEMORY

    def is_nas_available(self) -> bool:
        """检查 NAS 是否挂载"""
        return self.nas_path.exists()

    def get_latest_summary(self, days: int = 7) -> list[dict]:
        """获取最近 N 天的 SentientOS 摘要"""
        if not self.is_nas_available():
            return []

        summaries = []
        for f in sorted(
            self.nas_path.glob("daily_summary_*.md"), reverse=True
        ):
            if len(summaries) >= days:
                break
            summaries.append({
                "date": f.stem.replace("daily_summary_", ""),
                "path": str(f),
                "content": f.read_text(encoding="utf-8")[:2000],  # 截取前2000字符
            })
        return summaries

    def generate_context_injection(self) -> str:
        """生成可以注入 WorkBuddy 对话上下文的知识摘要"""
        summaries = self.get_latest_summary(days=3)
        if not summaries:
            return ""

        lines = [
            "<!-- SentientOS Context (auto-generated by sentient-nas-bridge) -->",
            f"## 最近 {len(summaries)} 天 SentientOS 知识摘要",
            "",
        ]
        for s in summaries:
            lines.append(f"### {s['date']}")
            lines.append(s['content'])
            lines.append("")

        context = "\n".join(lines)
        CONTEXT_FILE.write_text(context, encoding="utf-8")
        return context

    def sync_workbuddy_to_nas(self) -> bool:
        """将 WorkBuddy 工作日志同步到 NAS（供 SentientOS 下次引用）"""
        if not self.is_nas_available():
            return False

        wb_export = self.nas_path / "workbuddy_logs"
        wb_export.mkdir(parents=True, exist_ok=True)

        # 复制今天的日志
        today = datetime.now().strftime("%Y-%m-%d")
        today_log = self.wb_memory / f"{today}.md"
        if today_log.exists():
            shutil.copy2(today_log, wb_export / f"{today}.md")

        # 复制 MEMORY.md
        if WBMEMORY_FILE.exists():
            shutil.copy2(WBMEMORY_FILE, wb_export / "MEMORY.md")

        return True

    def status_report(self) -> dict:
        """生成状态报告"""
        return {
            "nas_available": self.is_nas_available(),
            "nas_path": str(self.nas_path),
            "sentient_data_count": len(list(SENTIENT_DATA.glob("*"))) if self.is_nas_available() else 0,
            "latest_summaries": len(self.get_latest_summary(7)),
            "wb_memory_path": str(self.wb_memory),
        }


if __name__ == "__main__":
    bridge = MemoryBridge()
    report = bridge.status_report()
    print(json.dumps(report, indent=2, ensure_ascii=False))
